"""French NAF rév. 2 activity codes used by the industry taxonomy, with their official labels."""

from __future__ import annotations

NAF_LABELS: dict[str, str] = {
    "10.71C": "Boulangerie et boulangerie-pâtisserie",
    "18.12Z": "Autre imprimerie (labeur)",
    "18.13Z": "Activités de pré-presse",
    "22.29A": "Fabrication de pièces techniques à base de matières plastiques",
    "25.11Z": "Fabrication de structures métalliques et de parties de structures",
    "25.62B": "Mécanique industrielle",
    "28.29B": "Fabrication d'autres machines d'usage général",
    "33.12Z": "Réparation de machines et équipements mécaniques",
    "41.10A": "Promotion immobilière de logements",
    "41.20A": "Construction de maisons individuelles",
    "41.20B": "Construction d'autres bâtiments",
    "43.21A": "Travaux d'installation électrique dans tous locaux",
    "43.22A": "Travaux d'installation d'eau et de gaz en tous locaux",
    "43.22B": "Travaux d'installation d'équipements thermiques et de climatisation",
    "43.32A": "Travaux de menuiserie bois et PVC",
    "43.39Z": "Autres travaux de finition",
    "43.99C": "Travaux de maçonnerie générale et gros œuvre de bâtiment",
    "45.11Z": "Commerce de voitures et de véhicules automobiles légers",
    "45.19Z": "Commerce d'autres véhicules automobiles",
    "45.20A": "Entretien et réparation de véhicules automobiles légers",
    "46.18Z": "Intermédiaires spécialisés dans le commerce d'autres produits spécifiques",
    "46.49Z": "Commerce de gros (commerce interentreprises) d'autres biens domestiques",
    "46.69B": "Commerce de gros (commerce interentreprises) de fournitures et équipements industriels divers",
    "46.90Z": "Commerce de gros (commerce interentreprises) non spécialisé",
    "47.19B": "Autres commerces de détail en magasin non spécialisé",
    "47.59B": "Commerce de détail d'autres équipements du foyer",
    "47.71Z": "Commerce de détail d'habillement en magasin spécialisé",
    "47.73Z": "Commerce de détail de produits pharmaceutiques en magasin spécialisé",
    "47.77Z": "Commerce de détail d'articles d'horlogerie et de bijouterie en magasin spécialisé",
    "47.78C": "Autres commerces de détail spécialisés divers",
    "47.91A": "Vente à distance sur catalogue général",
    "47.91B": "Vente à distance sur catalogue spécialisé",
    "49.41A": "Transports routiers de fret interurbains",
    "49.41B": "Transports routiers de fret de proximité",
    "52.10B": "Entreposage et stockage non frigorifique",
    "52.29A": "Messagerie, fret express",
    "52.29B": "Affrètement et organisation des transports",
    "55.10Z": "Hôtels et hébergement similaire",
    "55.20Z": "Hébergement touristique et autre hébergement de courte durée",
    "56.10A": "Restauration traditionnelle",
    "56.10B": "Cafétérias et autres libres-services",
    "56.10C": "Restauration de type rapide",
    "56.21Z": "Services des traiteurs",
    "56.30Z": "Débits de boissons",
    "58.21Z": "Édition de jeux électroniques",
    "58.29A": "Édition de logiciels système et de réseau",
    "58.29B": "Édition de logiciels outils de développement et de langages",
    "58.29C": "Édition de logiciels applicatifs",
    "59.11A": "Production de films et de programmes pour la télévision",
    "59.11B": "Production de films institutionnels et publicitaires",
    "59.11C": "Production de films pour le cinéma",
    "59.12Z": "Post-production de films cinématographiques, de vidéo et de programmes de télévision",
    "62.01Z": "Programmation informatique",
    "62.02A": "Conseil en systèmes et logiciels informatiques",
    "62.02B": "Tierce maintenance de systèmes et d'applications informatiques",
    "62.03Z": "Gestion d'installations informatiques",
    "62.09Z": "Autres activités informatiques",
    "63.11Z": "Traitement de données, hébergement et activités connexes",
    "63.12Z": "Portails Internet",
    "66.19B": "Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite, n.c.a.",
    "66.22Z": "Activités des agents et courtiers d'assurances",
    "66.30Z": "Gestion de fonds",
    "68.20B": "Location de terrains et d'autres biens immobiliers",
    "68.31Z": "Agences immobilières",
    "68.32A": "Administration d'immeubles et autres biens immobiliers",
    "69.10Z": "Activités juridiques",
    "69.20Z": "Activités comptables",
    "70.21Z": "Conseil en relations publiques et communication",
    "70.22Z": "Conseil pour les affaires et autres conseils de gestion",
    "71.11Z": "Activités d'architecture",
    "71.12B": "Ingénierie, études techniques",
    "72.19Z": "Recherche-développement en autres sciences physiques et naturelles",
    "73.11Z": "Activités des agences de publicité",
    "73.12Z": "Régie publicitaire de médias",
    "73.20Z": "Études de marché et sondages",
    "74.10Z": "Activités spécialisées de design",
    "74.20Z": "Activités photographiques",
    "74.90B": "Activités spécialisées, scientifiques et techniques diverses",
    "75.00Z": "Activités vétérinaires",
    "78.10Z": "Activités des agences de placement de main-d'œuvre",
    "78.20Z": "Activités des agences de travail temporaire",
    "78.30Z": "Autre mise à disposition de ressources humaines",
    "79.11Z": "Activités des agences de voyage",
    "79.12Z": "Activités des voyagistes",
    "79.90Z": "Autres services de réservation et activités connexes",
    "81.21Z": "Nettoyage courant des bâtiments",
    "81.22Z": "Autres activités de nettoyage des bâtiments et nettoyage industriel",
    "81.29B": "Autres activités de nettoyage n.c.a.",
    "82.11Z": "Services administratifs combinés de bureau",
    "82.30Z": "Organisation de foires, salons professionnels et congrès",
    "85.51Z": "Enseignement de disciplines sportives et d'activités de loisirs",
    "85.59A": "Formation continue d'adultes",
    "85.59B": "Autres enseignements",
    "85.60Z": "Activités de soutien à l'enseignement",
    "86.10Z": "Activités hospitalières",
    "86.21Z": "Activité des médecins généralistes",
    "86.22B": "Activités chirurgicales",
    "86.22C": "Autres activités des médecins spécialistes",
    "86.23Z": "Pratique dentaire",
    "86.90E": "Activités des professionnels de la rééducation, de l'appareillage et des pédicures-podologues",
    "88.99B": "Action sociale sans hébergement n.c.a.",
    "90.02Z": "Activités de soutien au spectacle vivant",
    "93.11Z": "Gestion d'installations sportives",
    "93.12Z": "Activités de clubs de sports",
    "93.13Z": "Activités des centres de culture physique",
    "93.19Z": "Autres activités liées au sport",
    "93.29Z": "Autres activités récréatives et de loisirs",
    "94.99Z": "Autres organisations fonctionnant par adhésion volontaire",
    "95.11Z": "Réparation d'ordinateurs et d'équipements périphériques",
    "96.02A": "Coiffure",
    "96.02B": "Soins de beauté",
    "96.04Z": "Entretien corporel",
    "96.09Z": "Autres services personnels n.c.a.",
}


def naf_label(code: str | None) -> str | None:
    if not code:
        return None
    return NAF_LABELS.get(code.strip().upper())


def naf_category(code: str | None) -> str | None:
    """'73.11Z' → '73.11Z Activités des agences de publicité' (code alone when the label is unknown)."""
    if not code:
        return None
    label = naf_label(code)
    return f"{code} {label}" if label else code
