"""email intelligence engine

* ``domain_profiles`` — Domain Intelligence Profile per domain (provider, MX, catch-all, SMTP behaviour,
  dominant pattern, evidence), global and reused across contacts, campaigns and workspaces.
* ``domain_email_samples`` — real addresses observed per domain (website, GitHub, RDAP, import, SMTP-verified).
* ``domain_email_patterns`` — ``share``, ``last_confirmed_at``, ``last_failed_at``.
* ``smtp_health`` — health of our SMTP verification path (global / per provider).
* ``email_verification_requests`` — deep-path queue, processed in per-domain SMTP batches with backoff.
* ``email_resolver_stats`` — empirical precision/latency/cost per resolver, source, pattern, technique.
* ``email_resolutions`` — per-resolution log (fast/deep path, probes, cache hits, duration).
* Email statuses ``LIKELY_SAFE`` and ``TEMPORARY_UNKNOWN``; SMTP result ``temporary``.

Revision ID: 4678d41bd34a
Revises: 7f6a512b9445
Create Date: 2026-10-06 06:25:42.992833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4678d41bd34a'
down_revision: Union[str, Sequence[str], None] = '7f6a512b9445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_STATUS_OLD = ["SAFE", "RISKY", "CATCH_ALL", "UNKNOWN", "INVALID"]
_STATUS_NEW = ["SAFE", "LIKELY_SAFE", "RISKY", "CATCH_ALL", "UNKNOWN", "TEMPORARY_UNKNOWN", "INVALID"]
_SMTP_OLD = ["accepted", "rejected", "unknown", "timeout", "blocked", "not_attempted"]
_SMTP_NEW = ["accepted", "rejected", "temporary", "unknown", "timeout", "blocked", "not_attempted"]
# Full constraint names as created by the naming convention (ck_<table>_<enum name>).
_ENUM_CHECKS_NEW = [
    ("emails", "status", "ck_emails_emailstatus", _STATUS_NEW),
    ("emails", "smtp_result", "ck_emails_smtpresult", _SMTP_NEW),
    ("email_checks", "status", "ck_email_checks_email_check_status", _STATUS_NEW),
    ("email_checks", "smtp_result", "ck_email_checks_email_check_smtp", _SMTP_NEW),
]
_ENUM_CHECKS_OLD = [(t, c, n, _STATUS_OLD if c == "status" else _SMTP_OLD) for t, c, n, _ in _ENUM_CHECKS_NEW]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_profiles',
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('provider', sa.Enum('google_workspace', 'microsoft_365', 'zoho', 'ovh', 'ionos', 'gandi', 'infomaniak', 'o2switch', 'proton', 'yandex', 'fastmail', 'icloud', 'amazon_ses', 'mailgun', 'secure_gateway', 'self_hosted', 'none', 'unknown', name='mailprovider', native_enum=False, create_constraint=True, length=48), server_default='unknown', nullable=False),
    sa.Column('mx_hosts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('has_mx', sa.Boolean(), nullable=True),
    sa.Column('accepts_mail', sa.Boolean(), nullable=True),
    sa.Column('catch_all', sa.Boolean(), nullable=True),
    sa.Column('catch_all_confidence', sa.Float(), nullable=True),
    sa.Column('catch_all_method', sa.Text(), nullable=True),
    sa.Column('catch_all_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('smtp_reachable', sa.Boolean(), nullable=True),
    sa.Column('smtp_last_result', sa.Text(), nullable=True),
    sa.Column('greylisting_seen', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('smtp_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dominant_pattern', sa.Text(), nullable=True),
    sa.Column('dominant_pattern_confidence', sa.Float(), nullable=True),
    sa.Column('named_samples', sa.Integer(), server_default='0', nullable=False),
    sa.Column('observed_emails', sa.Integer(), server_default='0', nullable=False),
    sa.Column('github_org', sa.Text(), nullable=True),
    sa.Column('website_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rdap_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mx_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('domain', name=op.f('pk_domain_profiles'))
    )
    op.create_table('email_resolver_stats',
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confirmed_correct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confirmed_wrong', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inconclusive', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms_total', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('cost_usd_total', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('dimension', 'key', name=op.f('pk_email_resolver_stats'))
    )
    op.create_table('smtp_health',
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('HEALTHY', 'DEGRADED', 'BLOCKED', 'UNKNOWN', name='smtphealthstate', native_enum=False, create_constraint=True, length=48), server_default='UNKNOWN', nullable=False),
    sa.Column('window', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scope', name=op.f('pk_smtp_health'))
    )
    op.create_table('domain_email_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('local_part', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('is_role', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.Enum('website', 'github', 'rdap', 'import', 'user', 'smtp_verified', 'search', name='emailevidencesource', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='0.9', nullable=False),
    sa.Column('times_seen', sa.Integer(), server_default='1', nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_domain_email_samples_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_email_samples')),
    sa.UniqueConstraint('domain', 'address', 'source', name=op.f('uq_domain_email_samples_domain_address_source'))
    )
    op.create_index('ix_domain_email_samples_domain', 'domain_email_samples', ['domain'], unique=False)
    op.create_table('email_resolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('path', sa.Enum('cache', 'fast', 'deep', name='emailresolutionpath', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('status', sa.Enum('SAFE', 'LIKELY_SAFE', 'RISKY', 'CATCH_ALL', 'UNKNOWN', 'TEMPORARY_UNKNOWN', 'INVALID', name='email_resolution_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('resolver', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('candidates_considered', sa.Integer(), server_default='0', nullable=False),
    sa.Column('smtp_probes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_hits', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_email_resolutions_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_email_resolutions_person_id_people'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_email_resolutions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_resolutions'))
    )
    op.create_index('ix_email_resolutions_created', 'email_resolutions', ['created_at'], unique=False)
    op.create_index('ix_email_resolutions_domain', 'email_resolutions', ['domain'], unique=False)
    op.create_index(op.f('ix_email_resolutions_workspace_id'), 'email_resolutions', ['workspace_id'], unique=False)
    op.create_table('email_verification_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'retry', 'done', 'cancelled', name='verificationrequeststatus', native_enum=False, create_constraint=True, length=48), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provisional_status', sa.Enum('SAFE', 'LIKELY_SAFE', 'RISKY', 'CATCH_ALL', 'UNKNOWN', 'TEMPORARY_UNKNOWN', 'INVALID', name='evr_provisional_status', native_enum=False, create_constraint=True, length=48), nullable=True),
    sa.Column('provisional_confidence', sa.Float(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('deliver_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_email_verification_requests_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_email_verification_requests_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_email_verification_requests_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_email_verification_requests_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_requests'))
    )
    op.create_index(op.f('ix_email_verification_requests_workspace_id'), 'email_verification_requests', ['workspace_id'], unique=False)
    op.create_index('ix_evr_domain_due', 'email_verification_requests', ['domain', 'status', 'next_attempt_at'], unique=False)
    op.create_index('uq_evr_active_person', 'email_verification_requests', ['workspace_id', 'person_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'processing', 'retry')"))
    op.add_column('domain_email_patterns', sa.Column('share', sa.Float(), server_default='0', nullable=False))
    op.add_column('domain_email_patterns', sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('domain_email_patterns', sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # New email statuses / SMTP result (varchar + CHECK enums: recreate the constraints).
    for table, column, name, values in _ENUM_CHECKS_NEW:
        op.drop_constraint(op.f(name), table, type_="check")
        op.create_check_constraint(op.f(name), table, sa.column(column).in_(values))



def downgrade() -> None:
    """Downgrade schema."""

    op.execute("UPDATE emails SET status = 'RISKY' WHERE status = 'LIKELY_SAFE'")
    op.execute("UPDATE emails SET status = 'UNKNOWN' WHERE status = 'TEMPORARY_UNKNOWN'")
    op.execute("UPDATE email_checks SET status = 'RISKY' WHERE status = 'LIKELY_SAFE'")
    op.execute("UPDATE email_checks SET status = 'UNKNOWN' WHERE status = 'TEMPORARY_UNKNOWN'")
    op.execute("UPDATE emails SET smtp_result = 'unknown' WHERE smtp_result = 'temporary'")
    op.execute("UPDATE email_checks SET smtp_result = 'unknown' WHERE smtp_result = 'temporary'")
    for table, column, name, values in _ENUM_CHECKS_OLD:
        op.drop_constraint(op.f(name), table, type_="check")
        op.create_check_constraint(op.f(name), table, sa.column(column).in_(values))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain_email_patterns', 'last_failed_at')
    op.drop_column('domain_email_patterns', 'last_confirmed_at')
    op.drop_column('domain_email_patterns', 'share')
    op.drop_index('uq_evr_active_person', table_name='email_verification_requests', postgresql_where=sa.text("status IN ('pending', 'processing', 'retry')"))
    op.drop_index('ix_evr_domain_due', table_name='email_verification_requests')
    op.drop_index(op.f('ix_email_verification_requests_workspace_id'), table_name='email_verification_requests')
    op.drop_table('email_verification_requests')
    op.drop_index(op.f('ix_email_resolutions_workspace_id'), table_name='email_resolutions')
    op.drop_index('ix_email_resolutions_domain', table_name='email_resolutions')
    op.drop_index('ix_email_resolutions_created', table_name='email_resolutions')
    op.drop_table('email_resolutions')
    op.drop_index('ix_domain_email_samples_domain', table_name='domain_email_samples')
    op.drop_table('domain_email_samples')
    op.drop_table('smtp_health')
    op.drop_table('email_resolver_stats')
    op.drop_table('domain_profiles')
    # ### end Alembic commands ###
